### PR TITLE
Use FIND_PACKAGE(Qt5 COMPONENTS OpenGL REQUIRED) instead of

### PR DESCRIPTION
**Pull request by KangLin**
FIND_PACKAGE(Qt5OpenGL REQUIRED)
Use FIND_PACKAGE(Qt5 COMPONENTS WebKitWidgets QUIET) instead of
FIND_PACKAGE(Qt5WebKitWidgets QUIET)

### CODE REVIEW

**Comment by mathieu** [comment]
Hi @KangLin,

Could you make this pull request on topic/Qt4 ?

-M

**Comment by a17r** [comment]
Why would you do that?

**Comment by KangLin** [comment]
> Why would you do that?

Simplify the parameters, only need Qt5_DIR

**Comment by KangLin** [comment]
> Hi @KangLin,
> Could you make this pull request on topic/Qt4 ?
> -M

Sorry, I don't use Qt4.

**Comment by mathieu** [comment]
This is not relevant on master branch

**Comment by KangLin** [comment]
Is this support Qt4?

**Pull request closed without merging**
