### PR TITLE
Use include/osgQt also for osgQt5

### PR DESCRIPTION
**Pull request by manisandro**
As a followup to b7d1d036812a71a065d385f451e252b78d7d5d77, since the osgQt4 and osgQt5 headers are identical, I think it is better to use include/osgQt also for osgQt5, given that most osgQt consumers include their headers via `#include <osgQt/...>`.

### CODE REVIEW

**Comment by manisandro** [comment]
Scratch that, there is `#define OSGQT_QT_VERSION` in `osgQt/Version`. The only other solution I see is following the convention a number of packages/distros use in installing the headers to `include/qt5/<package>`. This means that consumers might need to tweak their build scripts, but at least the `#include`s can remain the same.

**Comment by manisandro** [comment]
Or maybe one can do without OSGQT_QT_VERSION and keep the headers identical? Given that the library names now differ, the risk of mixing up qt versions is pretty small.

**Comment by manisandro** [comment]
So I actually think that `include/osgQt` for both qt4 and qt5 and dropping `osgQt/Version` is the least invasive option.

**Comment by marache** [comment]
Hi @manisandro 
Does that mean that you can't have both Qt4 and Qt5 headers intalled at the same time ?

**Comment by manisandro** [comment]
@marache Well the headers are identical for both Qt4 and Qt5, so it is merely a question how you deal with packaging them. RPM supports file co-ownership, meaning that multiple packages can own the same file as long as the file is identical. I'm not sure if DEB supports something similar, but if not you can still have a subpackage common to both Qt4 and Qt5 which pulls in the headers.

**Pull request merged**
