### PR TITLE
Feature/osgQOpenGL

### PR DESCRIPTION
**Pull request by mathieu**
Qt5's preferred way of handling GL

### CODE REVIEW

**Comment by gusmd** [comment]
Hey @mathieu this is really interesting. Are there any plans to make this the "official" way, i.e., officially deprecating the `QGLWidget`-based osgQt viewer?

**Comment by mathieu** [comment]
Yes I want to, but I need to do some work on preserving current master for Qt4 compatibility

**Comment by gusmd** [comment]
Just an idea, but could you have a new branch specifically for that? E.g., create a new branch `Qt4` out of the current master,, and merge this into master? Then people who need Qt4 support simply use the `Qt4` branch?

**Comment by mathieu** [comment]
I created a topic/Qt4 branch to keep current master available to Qt4 users

**Pull request merged**
